"""
JalRakshak — ORM Model: WaterSample

Stores:
- Administrative/location information
- Sampling information
- Water-quality measurements
- Deterministic rule-engine classification
- Audit/import metadata

IMPORTANT:
Classification fields are generated by the deterministic rule engine.
Gemini must never modify these safety fields.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    func,
)

from app.database import Base


class WaterSample(Base):
    __tablename__ = "water_samples"

    # ── Identity ──────────────────────────────────────────────────────────────
    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    sample_id = Column(
        String(64),
        unique=True,
        nullable=True,
        index=True,
    )

    # ── Administrative Location ──────────────────────────────────────────────
    state_ut = Column(
        String(128),
        nullable=False,
        index=True,
    )

    district = Column(
        String(128),
        nullable=False,
        index=True,
    )

    village = Column(
        String(256),
        nullable=True,
    )

    water_source_type = Column(
        String(64),
        nullable=True,
        index=True,
    )

    # ── Temporal Information ──────────────────────────────────────────────────
    season_cycle = Column(
        String(64),
        nullable=True,
        index=True,
    )

    sample_date = Column(
        String(32),
        nullable=True,
    )

    # ── Geospatial Information ────────────────────────────────────────────────
    #
    # Many dataset records may not have exact GPS coordinates.
    # location_type identifies whether the location is GPS-based
    # or administrative/centroid-based.
    #
    latitude = Column(
        Float,
        nullable=True,
    )

    longitude = Column(
        Float,
        nullable=True,
    )

    location_type = Column(
        String(32),
        nullable=True,
    )

    # ── Physical Parameters ───────────────────────────────────────────────────
    #
    # pH is dimensionless.
    # Turbidity is NTU.
    # TDS, hardness and chloride are mg/L.
    #
    ph = Column(
        Float,
        nullable=True,
    )

    turbidity_ntu = Column(
        Float,
        nullable=True,
    )

    tds_mg_l = Column(
        Float,
        nullable=True,
    )

    total_hardness_mg_l = Column(
        Float,
        nullable=True,
    )

    chloride_mg_l = Column(
        Float,
        nullable=True,
    )

    # ── Chemical Parameters ───────────────────────────────────────────────────
    #
    # Fluoride, nitrate and iron are stored in mg/L.
    #
    # Arsenic and uranium are stored in both:
    # - original/source unit: µg/L
    # - canonical converted unit: mg/L
    #
    # This preserves traceability while allowing the rule engine
    # to operate on standardized units.
    #
    fluoride_mg_l = Column(
        Float,
        nullable=True,
    )

    arsenic_mg_l = Column(
        Float,
        nullable=True,
    )

    arsenic_ug_l = Column(
        Float,
        nullable=True,
    )

    nitrate_mg_l = Column(
        Float,
        nullable=True,
    )

    iron_mg_l = Column(
        Float,
        nullable=True,
    )

    uranium_ug_l = Column(
        Float,
        nullable=True,
    )

    uranium_mg_l = Column(
        Float,
        nullable=True,
    )

    # ── Microbiological Parameters ────────────────────────────────────────────
    #
    # The real CSV supplies:
    # fecal_coliform_MPN_100mL
    #
    # The current operational schema maps this source measurement
    # to e_coli_mpn for the existing biological rule pathway.
    #
    # IMPORTANT:
    # total_coliform_mpn remains separate and is NOT fabricated
    # when the CSV does not supply an independent total-coliform value.
    #
    e_coli_mpn = Column(
        Float,
        nullable=True,
    )

    total_coliform_mpn = Column(
        Float,
        nullable=True,
    )

    # ── Deterministic Classification ──────────────────────────────────────────
    #
    # These fields are generated by evaluate_sample().
    # They are NOT generated by Gemini.
    #
    alert_category = Column(
        String(64),
        nullable=True,
        index=True,
    )

    severity = Column(
        String(32),
        nullable=True,
        index=True,
    )

    action_code = Column(
        String(64),
        nullable=True,
        index=True,
    )

    # Critical anti-boiling safety invariant.
    #
    # Chemical hazard → True
    # Mixed chemical + biological → True
    #
    # Gemini cannot override this value.
    do_not_boil = Column(
        Boolean,
        default=False,
        nullable=False,
    )

    primary_contaminant = Column(
        String(128),
        nullable=True,
    )

    rule_reason = Column(
        Text,
        nullable=True,
    )

    # ── Audit / Import Metadata ───────────────────────────────────────────────
    created_at = Column(
        DateTime,
        default=func.now(),
        nullable=False,
    )

    import_batch = Column(
        String(64),
        nullable=True,
    )

    # ── Composite Indexes ─────────────────────────────────────────────────────
    #
    # Optimized for dashboard and filtering queries.
    #
    __table_args__ = (
        Index(
            "ix_state_category",
            "state_ut",
            "alert_category",
        ),

        Index(
            "ix_district_severity",
            "district",
            "severity",
        ),

        Index(
            "ix_source_category",
            "water_source_type",
            "alert_category",
        ),

        Index(
            "ix_action_dnb",
            "action_code",
            "do_not_boil",
        ),

        Index(
            "ix_state_district",
            "state_ut",
            "district",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<WaterSample "
            f"id={self.id} "
            f"sample_id={self.sample_id!r} "
            f"state={self.state_ut!r} "
            f"district={self.district!r} "
            f"category={self.alert_category!r}>"
        )